backend:
  name: github
  repo: ssayi91/Pasi-Dental
  branch: main

media_folder: "images/uploads"  # Where uploaded images are stored in your repo
public_folder: "/images/uploads"  # Public URL path to access images

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Blog Content", name: "body", widget: "markdown"}
